### ISSUE TITLE
Comment cosmetics

### ISSUE THREAD

**Issue by idstudiolab** [id-studiolab/pomodoro#11]
It is much appreciated if the changes I made up to 06 can end up in the master. All code have been verified on my local board to compile and work correctly.

**Comment by lorenzoromagnoli** [comment]
Sure, I can review that. 
@idstudiolab do you mind making a "pull request" when you want me to merge files into master? in this way it way faster for me to review the code and merge it.

**Comment by lorenzoromagnoli** [comment]
...and btw you have not pushed any code to the repo yet :)

**Comment by lorenzoromagnoli** [comment]
... and if you want to really dive into the dark side of git, here is a beautyful cheat sheet with all the terminal commands. http://files.zeroturnaround.com/pdf/zt_git_cheat_sheet.pdf

**Comment by idstudiolab** [comment]
Brilliant! Now I see the state machine I can act better next time  ;-)
