### ISSUE TITLE
fastled vs chainable led

### ISSUE THREAD

**Issue by lorenzoromagnoli** [id-studiolab/pomodoro#3]
I'm opening a new issue so that we keep them divided.

Reguarding fastled, indeed I was about to ask you how do you feel about it. I don't particularly love the fastled APIs, but chainable led on the other hand is quite buggy and has some inconsistencies.

For example [here](https://github.com/id-studiolab/pomodoro/blob/bb1e681823aac657f5a8dba4f51e46c5faf5bab6/arduino_code/04_chainable_led_fade_change_color_with_pot/04_chainable_led_fade_change_color_with_pot.ino#L29), when using the setColorHSB() function, the parameters (hue, saturation, brightness) are supposed to go between 0 and 1 instead of 0-255. Moreover if you increase the brightness above 0.5 the any colors becomes white.  

I think we have several options on how to proced reguarding the choice of the library to use: 
1) I do all the live coding exercises using chainable led, and explain it's limitation when I find bugs or strange behaviours.  Then, when I introduce the class to the advanced fading example I also mention that this other library exists and they can see how it could have been used in replacement for chainable led (in the end I already ported all the exercises from 1to 5 from chainable to fastled)

2) we forget about the chainableled library and we do fastled from the beginning

How do you feel about this?

**Comment by idstudiolab** [comment]
As per offline discussion - I am fine with bringing in the FastLED library after an initial Chainable LED example.
