### ISSUE TITLE
Bring the new test code to the master branch

### ISSUE THREAD

**Issue by idstudiolab** [id-studiolab/pomodoro#7]
I have updated the 00_test_input_output code in my helping out branch.
Found a potential issue with different versions of the chainable_led library. I am using one that needs a leds.init() in the setup() (otherwise you will see a beautiful pink color that does not change).
Goodluck!

**Comment by idstudiolab** [comment]
Just checked, the ChainableLED library linked from the Seeedstudio wiki pages also has the leds.init() in the setup(). I know from passed experiences that there exists a ChainableLED library that is configure to do the init in the constructor of the class (so you do not have to do it in the setup()).

https://github.com/pjpmarques/ChainableLED

**Comment by lorenzoromagnoli** [comment]
In the video instructions, I explain how to download the library using the Arduino library manager. 
It seems that the library which comes with the library manager doesn't need the leds.init() in the setup and actually if you use it the code doesn't compile. 

I'll add a comment in the example code.

Thanks for checking
